title:              Singular Voice
email:              a.hassanzadeh.h@gmail.com
description:        Thoughts of a software engineer that abandoned from his favorite world
author:             Amir
baseurl:            ""

# Social Profiles
#twitter_username:   SBootstrap
github_username:    singularvoice
#facebook_username:  StartBootstrap
instagram_username:
linkedin_username: a-hassanzadeh-h

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

sass:
  sass_dir: _sass
  style: compressed
